const countryList = {
  "USD": "US",
  "AED": "AE",
  "AFN": "AF",
  "ALL": "AL",
  "AMD": "AM",
  "ANG": "AN",
  "AOA": "AO",
  "ARS": "AR",
  "AUD": "AU",
  "AWG": "AW",   // not in 2nd list, kept ISO style
  "AZN": "AZ",
  "BAM": "BA",
  "BBD": "BB",
  "BDT": "BD",
  "BGN": "BG",
  "BHD": "BH",
  "BIF": "BI",
  "BMD": "BM",
  "BND": "BN",
  "BOB": "BO",
  "BRL": "BR",
  "BSD": "BS",
  "BTN": "BT",   // Bhutan (added ISO style)
  "BWP": "BW",
  "BYN": "BY",   // replaced with BY (Belarus)
  "BZD": "BZ",
  "CAD": "CA",
  "CDF": "CD",
  "CHF": "CH",
  "CLF": "CL",   // Chile (CLF not in 2nd list, mapped to CL)
  "CLP": "CL",
  "CNH": "CN",   // same as CNY
  "CNY": "CN",
  "COP": "CO",
  "CRC": "CR",
  "CUP": "CU",
  "CVE": "CV",
  "CZK": "CZ",
  "DJF": "DJ",
  "DKK": "DK",
  "DOP": "DO",
  "DZD": "DZ",
  "EGP": "EG",
  "ERN": "ER",   // Eritrea (ISO style)
  "ETB": "ET",
  "EUR": "FR",
  "FJD": "FJ",
  "FKP": "FK",
  "FOK": "FO",   // Faroe Islands (ISO style)
  "GBP": "GB",
  "GEL": "GE",
  "GGP": "GG",
  "GHS": "GH",
  "GIP": "GI",
  "GMD": "GM",
  "GNF": "GN",
  "GTQ": "GT",
  "GYD": "GY",
  "HKD": "HK",
  "HNL": "HN",
  "HRK": "HR",
  "HTG": "HT",
  "HUF": "HU",
  "IDR": "ID",
  "ILS": "IL",
  "IMP": "IM",   // Isle of Man (ISO style)
  "INR": "IN",
  "IQD": "IQ",
  "IRR": "IR",
  "ISK": "IS",
  "JEP": "JE",   // Jersey (ISO style)
  "JMD": "JM",
  "JOD": "JO",
  "JPY": "JP",
  "KES": "KE",
  "KGS": "KG",
  "KHR": "KH",
  "KID": "KI",   // Kiribati (ISO style)
  "KMF": "KM",
  "KRW": "KR",
  "KWD": "KW",
  "KYD": "KY",
  "KZT": "KZ",
  "LAK": "LA",
  "LBP": "LB",
  "LKR": "LK",
  "LRD": "LR",
  "LSL": "LS",
  "LYD": "LY",
  "MAD": "MA",
  "MDL": "MD",
  "MGA": "MG",
  "MKD": "MK",
  "MMK": "MM",
  "MNT": "MN",
  "MOP": "MO",
  "MRU": "MR",   // Mauritania (ISO style)
  "MUR": "MU",
  "MVR": "MV",
  "MWK": "MW",
  "MXN": "MX",
  "MYR": "MY",
  "MZN": "MZ",
  "NAD": "NA",
  "NGN": "NG",
  "NIO": "NI",
  "NOK": "NO",   // Norway (BV in 2nd list but ISO is NO)
  "NPR": "NP",
  "NZD": "NZ",
  "OMR": "OM",
  "PAB": "PA",
  "PEN": "PE",
  "PGK": "PG",
  "PHP": "PH",
  "PKR": "PK",
  "PLN": "PL",
  "PYG": "PY",
  "QAR": "QA",
  "RON": "RO",
  "RSD": "RS",
  "RUB": "RU",
  "RWF": "RW",
  "SAR": "SA",
  "SBD": "SB",
  "SCR": "SC",
  "SDG": "SD",
  "SEK": "SE",
  "SGD": "SG",
  "SHP": "SH",   // Saint Helena (ISO style)
  "SLE": "SL",   // Sierra Leone (ISO style)
  "SLL": "SL",
  "SOS": "SO",
  "SRD": "SR",
  "SSP": "SS",   // South Sudan (ISO style)
  "STN": "ST",
  "SYP": "SY",
  "SZL": "SZ",
  "THB": "TH",
  "TJS": "TJ",
  "TMT": "TM",
  "TND": "TN",
  "TOP": "TO",
  "TRY": "TR",
  "TTD": "TT",
  "TVD": "TV",   // Tuvalu (ISO style)
  "TWD": "TW",
  "TZS": "TZ",
  "UAH": "UA",
  "UGX": "UG",
  "UYU": "UY",
  "UZS": "UZ",
  "VES": "VE",   // Venezuela (VEF in 2nd list, mapped to VE)
  "VND": "VN",
  "VUV": "VU",
  "WST": "WS",   // Samoa (ISO style)
  "XAF": "CF",
  "XCD": "AG",
  "XCG": "CG",   // Congo (ISO style)
  "XDR": "XD",   // IMF SDR (custom)
  "XOF": "BE",
  "XPF": "NC",
  "YER": "YE",
  "ZAR": "ZA",
  "ZMW": "ZM",
  "ZWG": "ZW",   // Zimbabwe (ISO style)
  "ZWL": "ZW"
};
